const GET_ALBUMS = 'GET_ALBUMS';
const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
const GET_ALBUMS_FAILURE = 'GET_ALBUMS_FAILURE';
const SET_SEARCH_BAR = 'SET_SEARCH_BAR';

export {
    GET_ALBUMS,
    GET_ALBUMS_SUCCESS,
    GET_ALBUMS_FAILURE,
    SET_SEARCH_BAR
};